on:
  push:
    branches:
      - main

name: test

jobs:
  check-r2u:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        
      - name: Check
        uses: analythium/actions/pkgdown@v1.5

      - name: Install rsync 📚
        run: apt-get update && apt-get install -y rsync

      - name: Deploy site
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: docs
          clean: true
