on:
  push:
    branches:
      - test

name: test

jobs:
  test:
    runs-on: ubuntu-latest
    container: ghcr.io/analythium/actions:latest
    steps:

      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install dependencies
        run: deps-cli all

      - name: Check R package
        run: Rscript -e 'devtools::check(document=TRUE)'

      - name: Build pkgdown site
        run: Rscript -e 'pkgdown::build_site_github_pages(install=TRUE)'

      - name: Deploy site
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: docs
          clean: true
